In [1]:
import pandas as pd
import numpy as np

In [2]:
s_gains = pd.read_csv("../files/db_featmag_gains_S.csv")
p_gains = pd.read_csv("../files/db_featmag_gains_P.csv")

In [3]:
s_gains["phase"] = "S"
p_gains["phase"] = "P"

In [4]:
# # Get all channel ids from db
# all_chan_ids = s_gains.channel_id
# # Get the channel ids that do not have a feature mag gain - either 1C or was not in Ben's cat
# s_no_featmag_id = s_gains[np.isnan(s_gains["feat_mag_gains"])].channel_id
# # Get the channel ids that do have a P feature mag
# p_yes_fetmag_id = p_gains[~np.isnan(p_gains["feat_mag_gains"])].channel_id
# # Use the P row if there is a value in the P catalog but not the S
# p_ids_to_use = p_yes_fetmag_id[np.isin(p_yes_fetmag_id, s_no_featmag_id)]
# # Use the S other wise
# s_ids_to_use = all_chan_ids[~np.isin(all_chan_ids, p_ids_to_use)]
# assert len(p_ids_to_use) + len(s_ids_to_use) == len(all_chan_ids)
# summ_df = pd.concat([s_gains[s_gains["channel_id"].isin(s_ids_to_use)], p_gains[p_gains["channel_id"].isin(p_ids_to_use)]])
# print(summ_df["phase"].value_counts())
# print(merged_summ_df.sort_values("channel_id").equals(summ_df.sort_values("channel_id")))

In [5]:
merged_df = s_gains[["channel_id", "featmag_gain"]].merge(p_gains[["channel_id", "featmag_gain"]], on=["channel_id"], suffixes=("S", "P"))
# Use the P row if there is a value in the P catalog but not the S - should just be 1C stations or some that have P but no S picks
p_ids_to_use = merged_df[(~np.isnan(merged_df["featmag_gainP"])) & (np.isnan(merged_df["featmag_gainS"]))]["channel_id"]
merged_summ_df = pd.concat([s_gains[~s_gains["channel_id"].isin(p_ids_to_use)], p_gains[p_gains["channel_id"].isin(p_ids_to_use)]]).sort_values("channel_id")
assert len(merged_summ_df) == len(s_gains)

In [6]:
merged_summ_df["phase"].value_counts()

phase
S    418
P     54
Name: count, dtype: int64

In [7]:
merged_summ_df.head()

,channel_id,network,station,location,seed_code,channel_samp_rate,sensit_units,sensit_freq,sensit_val,gain_vel,receiver_lat,receiver_lon,channel_azimuth,channel_ondate,channel_offdate,simple_gain_vel,featmag_gain,featmag_gain_units,phase
59,1,PB,B945,,EH1,100.0,M/S,20.00,781398000.0,7.916178e+08,44.894001,-110.744102,212.5,2008-09-04 00:00:00,NaN,781398000.0,781398000.0,DU/M/S,S
60,2,PB,B945,,EH2,100.0,M/S,20.00,781398000.0,7.916178e+08,44.894001,-110.744102,302.5,2008-09-04 00:00:00,NaN,781398000.0,781398000.0,DU/M/S,S
61,3,PB,B945,,EHZ,100.0,M/S,20.00,781398000.0,7.916178e+08,44.894001,-110.744102,0.0,2008-09-04 00:00:00,NaN,781398000.0,781398000.0,DU/M/S,S
3,4,IW,FLWY,00,BH1,40.0,m/s,0.02,293920000.0,2.939199e+08,44.083002,-110.699888,2.8,2021-08-29 18:00:00,NaN,293920000.0,301720000.0,DU/M/S,S
7,5,IW,FLWY,00,BH2,40.0,m/s,0.02,293920000.0,2.939199e+08,44.083002,-110.699888,92.8,2021-08-29 18:00:00,NaN,293920000.0,301720000.0,DU/M/S,S

In [8]:
merged_summ_df[merged_summ_df["station"] == "FLWY"]

,channel_id,network,station,location,seed_code,channel_samp_rate,sensit_units,sensit_freq,sensit_val,gain_vel,receiver_lat,receiver_lon,channel_azimuth,channel_ondate,channel_offdate,simple_gain_vel,featmag_gain,featmag_gain_units,phase
3,4,IW,FLWY,00,BH1,40.0,m/s,0.02,2.939200e+08,2.939199e+08,44.083002,-110.699888,2.8,2021-08-29 18:00:00,NaN,2.939200e+08,3.017200e+08,DU/M/S,S
7,5,IW,FLWY,00,BH2,40.0,m/s,0.02,2.939200e+08,2.939199e+08,44.083002,-110.699888,92.8,2021-08-29 18:00:00,NaN,2.939200e+08,3.017200e+08,DU/M/S,S
13,6,IW,FLWY,00,BHZ,40.0,m/s,0.02,2.939200e+08,2.939199e+08,44.083002,-110.699888,0.0,2021-08-29 18:00:00,NaN,2.939200e+08,3.017200e+08,DU/M/S,S
2,377,IW,FLWY,00,BH1,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2020-01-30 20:00:00,2021-08-29 18:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
6,378,IW,FLWY,00,BH2,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,90.0,2020-01-30 20:00:00,2021-08-29 18:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
12,379,IW,FLWY,00,BHZ,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2020-01-30 20:00:00,2021-08-29 18:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
1,568,IW,FLWY,00,BH1,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2016-10-22 04:00:00,2020-01-30 20:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
5,569,IW,FLWY,00,BH2,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,90.0,2016-10-22 04:00:00,2020-01-30 20:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
11,570,IW,FLWY,00,BHZ,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2016-10-22 04:00:00,2020-01-30 20:00:00,4.624290e+08,4.624290e+08,DU/M/S,S
0,958,IW,FLWY,00,BH1,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,0.0,2013-07-25 14:46:00,2016-10-22 04:00:00,1.145990e+09,NaN,NaN,S
4,959,IW,FLWY,00,BH2,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,90.0,2013-07-25 14:46:00,2016-10-22 04:00:00,1.145990e+09,NaN,NaN,S
10,960,IW,FLWY,00,BHZ,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,0.0,2013-07-25 14:46:00,2016-10-22 04:00:00,1.145990e+09,1.258650e+09,DU/M/S,S
8,1168,IW,FLWY,,BHE,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,90.0,2007-03-16 16:46:00,2013-07-25 14:46:00,1.145990e+09,1.258650e+09,DU/M/S,S
9,1169,IW,FLWY,,BHN,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,0.0,2007-03-16 16:46:00,2013-07-25 14:46:00,1.145990e+09,1.258650e+09,DU/M/S,S
14,1170,IW,FLWY,,BHZ,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,0.0,2007-03-16 16:46:00,2013-07-25 14:46:00,1.145990e+09,1.258650e+09,DU/M/S,S

In [9]:
merged_summ_df.to_csv("../files/summary_db_featmag_gains.csv", index=False)